// <auto-generated />
using System;
using Microservicio_Paquete.AccessData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microservicio_Paquete.AccessData.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    partial class TemplateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Comentario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Destinoid")
                        .HasColumnType("int");

                    b.Property<string>("fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idDestino")
                        .HasColumnType("int");

                    b.Property<int>("idPasajero")
                        .HasColumnType("int");

                    b.Property<string>("mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Destinoid");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Destino", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("atractivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("historia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lugar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Destino");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.DestinoExcursion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Destinoid")
                        .HasColumnType("int");

                    b.Property<int?>("Excursionid")
                        .HasColumnType("int");

                    b.Property<int>("idDestino")
                        .HasColumnType("int");

                    b.Property<int>("idExcursion")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Destinoid");

                    b.HasIndex("Excursionid");

                    b.ToTable("DestinoExcursion");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.DestinoHotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Destinoid")
                        .HasColumnType("int");

                    b.Property<int?>("Hotelid")
                        .HasColumnType("int");

                    b.Property<int>("idDestino")
                        .HasColumnType("int");

                    b.Property<int>("idHotel")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Destinoid");

                    b.HasIndex("Hotelid");

                    b.ToTable("DestinoHotel");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Excursion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bloqueada")
                        .HasColumnType("bit");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Excursion");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.FormaPago", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("FormaPago");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.HabitacionHotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Hotelid")
                        .HasColumnType("int");

                    b.Property<int>("disponibles")
                        .HasColumnType("int");

                    b.Property<int>("idHotel")
                        .HasColumnType("int");

                    b.Property<int>("idTipoHabitacion")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Hotelid");

                    b.ToTable("HabitacionHotel");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Hotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("bloqueado")
                        .HasColumnType("bit");

                    b.Property<int>("estrellas")
                        .HasColumnType("int");

                    b.Property<int>("idDireccion")
                        .HasColumnType("int");

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sucursal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.HotelPension", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("HotelPension");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Paquete", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PaqueteEstadoid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("descuento")
                        .HasColumnType("int");

                    b.Property<string>("fechasalida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechavuelta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("idPaqueteEstado")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.Property<int>("totalnoches")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PaqueteEstadoid");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.PaqueteDestino", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Destinoid")
                        .HasColumnType("int");

                    b.Property<int?>("Paqueteid")
                        .HasColumnType("int");

                    b.Property<int>("idDestino")
                        .HasColumnType("int");

                    b.Property<int>("idPaquete")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Destinoid");

                    b.HasIndex("Paqueteid");

                    b.ToTable("PaqueteDestino");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.PaqueteEstado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("PaqueteEstado");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.PaqueteHotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HotelPensionid")
                        .HasColumnType("int");

                    b.Property<int?>("Hotelid")
                        .HasColumnType("int");

                    b.Property<int?>("Paqueteid")
                        .HasColumnType("int");

                    b.Property<int>("idHotel")
                        .HasColumnType("int");

                    b.Property<int>("idHotelPension")
                        .HasColumnType("int");

                    b.Property<int>("idPaquete")
                        .HasColumnType("int");

                    b.Property<int>("noches")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("HotelPensionid");

                    b.HasIndex("Hotelid");

                    b.HasIndex("Paqueteid");

                    b.ToTable("PaqueteHotel");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.PaqueteViaje", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Paqueteid")
                        .HasColumnType("int");

                    b.Property<int>("idPaquete")
                        .HasColumnType("int");

                    b.Property<int>("idViaje")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Paqueteid");

                    b.ToTable("PaqueteViaje");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FormaPagoid")
                        .HasColumnType("int");

                    b.Property<int?>("Paqueteid")
                        .HasColumnType("int");

                    b.Property<int>("idFormaPago")
                        .HasColumnType("int");

                    b.Property<int>("idPaquete")
                        .HasColumnType("int");

                    b.Property<int>("idPasajero")
                        .HasColumnType("int");

                    b.Property<bool>("pagado")
                        .HasColumnType("bit");

                    b.Property<int>("pasajeros")
                        .HasColumnType("int");

                    b.Property<int>("preciototal")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("FormaPagoid");

                    b.HasIndex("Paqueteid");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.ReservaExcursion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Excursionid")
                        .HasColumnType("int");

                    b.Property<int?>("Reservaid")
                        .HasColumnType("int");

                    b.Property<int>("idExcursion")
                        .HasColumnType("int");

                    b.Property<int>("idReserva")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Excursionid");

                    b.HasIndex("Reservaid");

                    b.ToTable("ReservaExcursion");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.ReservaHabitacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Hotelid")
                        .HasColumnType("int");

                    b.Property<int?>("Reservaid")
                        .HasColumnType("int");

                    b.Property<int?>("TipoHabitacionid")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("idHotel")
                        .HasColumnType("int");

                    b.Property<int>("idReserva")
                        .HasColumnType("int");

                    b.Property<int>("idTipoHabitacion")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Hotelid");

                    b.HasIndex("Reservaid");

                    b.HasIndex("TipoHabitacionid");

                    b.ToTable("ReservaHabitacion");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.TipoHabitacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("plazas")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TipoHabitacion");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.Destino", "Destino")
                        .WithMany("Comentarios")
                        .HasForeignKey("Destinoid");

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.DestinoExcursion", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.Destino", "Destino")
                        .WithMany("DestinoExcursiones")
                        .HasForeignKey("Destinoid");

                    b.HasOne("Microservicio_Paquete.Domain.Entities.Excursion", "Excursion")
                        .WithMany("DestinoExcursiones")
                        .HasForeignKey("Excursionid");

                    b.Navigation("Destino");

                    b.Navigation("Excursion");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.DestinoHotel", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.Destino", null)
                        .WithMany("DestinoHoteles")
                        .HasForeignKey("Destinoid");

                    b.HasOne("Microservicio_Paquete.Domain.Entities.Hotel", null)
                        .WithMany("DestinoHoteles")
                        .HasForeignKey("Hotelid");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.HabitacionHotel", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.Hotel", null)
                        .WithMany("HabitacionHoteles")
                        .HasForeignKey("Hotelid");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Paquete", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.PaqueteEstado", "PaqueteEstado")
                        .WithMany("Paquetes")
                        .HasForeignKey("PaqueteEstadoid");

                    b.Navigation("PaqueteEstado");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.PaqueteDestino", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.Destino", "Destino")
                        .WithMany("PaqueteDestinos")
                        .HasForeignKey("Destinoid");

                    b.HasOne("Microservicio_Paquete.Domain.Entities.Paquete", "Paquete")
                        .WithMany("PaqueteDestinos")
                        .HasForeignKey("Paqueteid");

                    b.Navigation("Destino");

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.PaqueteHotel", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.HotelPension", "HotelPension")
                        .WithMany("PaqueteHoteles")
                        .HasForeignKey("HotelPensionid");

                    b.HasOne("Microservicio_Paquete.Domain.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("Hotelid");

                    b.HasOne("Microservicio_Paquete.Domain.Entities.Paquete", "Paquete")
                        .WithMany("PaqueteHoteles")
                        .HasForeignKey("Paqueteid");

                    b.Navigation("Hotel");

                    b.Navigation("HotelPension");

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.PaqueteViaje", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.Paquete", "Paquete")
                        .WithMany("PaqueteViajes")
                        .HasForeignKey("Paqueteid");

                    b.Navigation("Paquete");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.FormaPago", "FormaPago")
                        .WithMany("Reservas")
                        .HasForeignKey("FormaPagoid");

                    b.HasOne("Microservicio_Paquete.Domain.Entities.Paquete", null)
                        .WithMany("Reservas")
                        .HasForeignKey("Paqueteid");

                    b.Navigation("FormaPago");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.ReservaExcursion", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.Excursion", "Excursion")
                        .WithMany("ReservaExcursiones")
                        .HasForeignKey("Excursionid");

                    b.HasOne("Microservicio_Paquete.Domain.Entities.Reserva", "Reserva")
                        .WithMany("ReservaExcursiones")
                        .HasForeignKey("Reservaid");

                    b.Navigation("Excursion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.ReservaHabitacion", b =>
                {
                    b.HasOne("Microservicio_Paquete.Domain.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("Hotelid");

                    b.HasOne("Microservicio_Paquete.Domain.Entities.Reserva", "Reserva")
                        .WithMany("ReservaHabitaciones")
                        .HasForeignKey("Reservaid");

                    b.HasOne("Microservicio_Paquete.Domain.Entities.TipoHabitacion", "TipoHabitacion")
                        .WithMany()
                        .HasForeignKey("TipoHabitacionid");

                    b.Navigation("Hotel");

                    b.Navigation("Reserva");

                    b.Navigation("TipoHabitacion");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Destino", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("DestinoExcursiones");

                    b.Navigation("DestinoHoteles");

                    b.Navigation("PaqueteDestinos");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Excursion", b =>
                {
                    b.Navigation("DestinoExcursiones");

                    b.Navigation("ReservaExcursiones");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.FormaPago", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Hotel", b =>
                {
                    b.Navigation("DestinoHoteles");

                    b.Navigation("HabitacionHoteles");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.HotelPension", b =>
                {
                    b.Navigation("PaqueteHoteles");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Paquete", b =>
                {
                    b.Navigation("PaqueteDestinos");

                    b.Navigation("PaqueteHoteles");

                    b.Navigation("PaqueteViajes");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.PaqueteEstado", b =>
                {
                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("Microservicio_Paquete.Domain.Entities.Reserva", b =>
                {
                    b.Navigation("ReservaExcursiones");

                    b.Navigation("ReservaHabitaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
